### ISSUE TITLE
assertThat is deprecated

### ISSUE THREAD

**Issue by joshuajeschek** [weichware10/util#16]
assertThat ist deprecated, und sollte ausgetauscht werden.
Tritt hier auf:
- [x] ConfigClientTest
- [x] ConfigLoaderTest
- [x] SpeicherUtilitiesTest

**Comment by TheDarkDesync** [comment]
[Lösung](https://jsparrow.github.io/rules/replace-j-unit-assert-that-with-hamcrest.html#code-changes)
`org.hamcrest.MatcherAssert.assertThat` anstatt `org.junit.Assert.assertThat`

**Comment by joshuajeschek** [comment]
> [Lösung](https://jsparrow.github.io/rules/replace-j-unit-assert-that-with-hamcrest.html#code-changes) `org.hamcrest.MatcherAssert.assertThat` anstatt `org.junit.Assert.assertThat`

👍
