### ISSUE TITLE
Änderungen ZoomMaps

### ISSUE THREAD

**Issue by joshuajeschek** [weichware10/util#27]
- [x] trialdata:
    - [x] int -> double
    - [x] double coordinates + double rasterSize
    - [x] double[4] viewport
- [x] configuration:
    - [x] question und imageurl beides in allgemeiner konfiguration
    - [x] imageurl statt imageurls

- [x] database util
    - [x] ganze Speichersachen anpassen

**Comment by justinexner** [comment]
Die 3 offenen Sachen habe ich glaube ausersehen nebenbei gemacht :)

**Comment by TheDarkDesync** [comment]
Muss zoomLevel nicht auch noch aus DataPoint entfernt werden, da wir jetzt den viewport haben oder vertue ich mich gerade
